name: Deploy

on:
  push:
    branch:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v1

      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::982195495700:role/serverless-laravel-deploy-staging
          aws-region: eu-west-1

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'cdk-serverless-laravel-staging'
          cdk_args: '--require-approval never'
          actions_comment: false